"""
Model Trainer for Automated LLM Finetuning Pipeline

This module provides the ModelTrainer class for finetuning Llama 3.2 3B models
on AWS SageMaker using training data generated by the SyntheticDataGenerator.

The ModelTrainer handles:
- Initiating SageMaker training jobs with LoRA configuration using JumpStart
- Determining optimal hyperparameters based on dataset analysis
- Monitoring training job status with polling
- Managing training artifacts and cleanup
- Error handling with retry logic
"""

import json
import logging
import time
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional

import boto3
import sagemaker
from sagemaker.jumpstart.estimator import JumpStartEstimator
from sagemaker.inputs import TrainingInput

from src.config_models import (
    DatasetAnalysis,
    PipelineConfig,
    TrainingResult
)
from src.logging_config import get_logger

# Configure module logger
logger = get_logger(__name__)


class ModelTrainer:
    """
    Finetunes Llama 3.2 3B models on AWS SageMaker.
    
    The ModelTrainer uses AWS SageMaker to finetune Llama models with LoRA
    (Low-Rank Adaptation) configuration. It supports:
    - Automatic hyperparameter optimization based on dataset size
    - Training job monitoring with polling
    - Training artifact management and cleanup
    - Error handling and retry logic
    
    Attributes:
        sagemaker_client: AWS SageMaker client for training operations
        config: Pipeline configuration with AWS settings and parameters
    
    Example:
        >>> from src.aws_client_manager import AWSClientManager
        >>> from src.configuration_manager import ConfigurationManager
        >>> 
        >>> # Initialize components
        >>> config_manager = ConfigurationManager()
        >>> pipeline_config = config_manager.load_pipeline_config()
        >>> aws_manager = AWSClientManager({'region': pipeline_config.aws_region})
        >>> sagemaker_client = aws_manager.get_sagemaker_client()
        >>> 
        >>> # Create trainer
        >>> trainer = ModelTrainer(sagemaker_client, pipeline_config)
        >>> 
        >>> # Train model
        >>> result = trainer.train_model(
        ...     training_data_path="event_files/training_data/dataset.jsonl",
        ...     use_case_name="customer_support"
        ... )
    """
    
    def __init__(
        self,
        sagemaker_client: Any,
        config: PipelineConfig
    ):
        """
        Initialize ModelTrainer with SageMaker client and configuration.
        
        Sets up the trainer with the necessary AWS SageMaker client for managing
        training jobs and the pipeline configuration containing training settings,
        instance types, and other operational parameters.
        
        Args:
            sagemaker_client: AWS SageMaker client instance for managing training jobs.
                            Should be obtained from AWSClientManager.
                            Can be a real boto3 client or a mock for testing.
            config: PipelineConfig instance containing AWS region, SageMaker role ARN,
                   training instance type, S3 bucket, and other pipeline parameters.
        
        Raises:
            ValueError: If sagemaker_client is None or config is None
            TypeError: If config is not a PipelineConfig instance
            AttributeError: If config is missing required attributes
        
        Example:
            >>> from src.aws_client_manager import AWSClientManager
            >>> from src.configuration_manager import ConfigurationManager
            >>> 
            >>> config_manager = ConfigurationManager()
            >>> pipeline_config = config_manager.load_pipeline_config()
            >>> aws_manager = AWSClientManager({'region': pipeline_config.aws_region})
            >>> sagemaker_client = aws_manager.get_sagemaker_client()
            >>> 
            >>> trainer = ModelTrainer(sagemaker_client, pipeline_config)
        """
        # Validate sagemaker_client parameter
        if sagemaker_client is None:
            raise ValueError("sagemaker_client cannot be None")
        
        # Validate config parameter
        if config is None:
            raise ValueError("config cannot be None")
        
        # Validate config is a PipelineConfig instance
        if not isinstance(config, PipelineConfig):
            raise TypeError(
                f"config must be a PipelineConfig instance, got {type(config).__name__}"
            )
        
        # Validate config has required attributes
        required_attrs = [
            'sagemaker_role_arn',
            'training_instance_type',
            'aws_region',
            's3_bucket',
            'base_model',
            'max_training_time_seconds',
            'max_retries',
            'initial_backoff_seconds',
            'max_backoff_seconds'
        ]
        
        missing_attrs = [attr for attr in required_attrs if not hasattr(config, attr)]
        if missing_attrs:
            raise AttributeError(
                f"config is missing required attributes: {', '.join(missing_attrs)}"
            )
        
        # Store client and configuration
        self.sagemaker_client = sagemaker_client
        self.config = config
        
        # Create SageMaker session for JumpStart
        boto_session = boto3.Session(region_name=self.config.aws_region)
        self.sagemaker_session = sagemaker.Session(boto_session=boto_session)
        
        logger.info(
            "ModelTrainer initialized",
            extra={
                "context": {
                    "region": self.config.aws_region,
                    "training_instance_type": self.config.training_instance_type,
                    "base_model": self.config.base_model,
                    "max_training_time_seconds": self.config.max_training_time_seconds,
                }
            }
        )
        
        logger.debug(
            "ModelTrainer configuration details",
            extra={
                "context": {
                    "sagemaker_role_arn": self.config.sagemaker_role_arn,
                    "s3_bucket": self.config.s3_bucket,
                    "max_retries": self.config.max_retries,
                    "initial_backoff_seconds": self.config.initial_backoff_seconds,
                    "max_backoff_seconds": self.config.max_backoff_seconds,
                }
            }
        )

    def train_model(
        self,
        training_data_path: str,
        use_case_name: str,
        hyperparameters: Optional[Dict] = None
    ) -> TrainingResult:
        """
        Start SageMaker training job and wait for completion.
        
        Initiates a SageMaker training job for finetuning Llama 3.2 3B model
        using the provided training data. The method:
        1. Uploads training data to S3
        2. Determines optimal hyperparameters (if not provided)
        3. Creates and starts a SageMaker training job with JumpStart
        4. Waits for training completion with polling
        5. Returns training results with job details
        
        The training uses LoRA (Low-Rank Adaptation) configuration for efficient
        finetuning. Hyperparameters are automatically determined based on dataset
        size if not explicitly provided.
        
        Args:
            training_data_path: Path to the JSONL file containing training examples.
                               Each line should be a JSON object with 'instruction',
                               'context', and 'response' fields.
            use_case_name: Name of the use case being trained. Used for naming
                          the training job and organizing artifacts.
            hyperparameters: Optional dictionary of training hyperparameters.
                           If None, hyperparameters will be automatically determined
                           based on dataset analysis. Common parameters include:
                           - epochs: Number of training epochs
                           - learning_rate: Learning rate for optimization
                           - batch_size: Training batch size
                           - lora_r: LoRA rank parameter
                           - lora_alpha: LoRA alpha parameter
        
        Returns:
            TrainingResult: Object containing training job details:
                - job_name: SageMaker training job name
                - model_artifact_s3_uri: S3 URI of the trained model artifact
                - training_time_seconds: Total training time in seconds
                - final_loss: Final training loss value
                - status: Training job status ('Completed', 'Failed', etc.)
                - error_message: Error message if training failed (None if successful)
        
        Raises:
            FileNotFoundError: If training_data_path does not exist
            ValueError: If training_data_path is empty or invalid
            RuntimeError: If training job fails or times out
            IOError: If unable to upload data to S3
        
        Example:
            >>> from src.aws_client_manager import AWSClientManager
            >>> from src.configuration_manager import ConfigurationManager
            >>> 
            >>> # Initialize components
            >>> config_manager = ConfigurationManager()
            >>> pipeline_config = config_manager.load_pipeline_config()
            >>> aws_manager = AWSClientManager({'region': pipeline_config.aws_region})
            >>> sagemaker_client = aws_manager.get_sagemaker_client()
            >>> 
            >>> # Create trainer
            >>> trainer = ModelTrainer(sagemaker_client, pipeline_config)
            >>> 
            >>> # Train model
            >>> result = trainer.train_model(
            ...     training_data_path="event_files/training_data/dataset.jsonl",
            ...     use_case_name="customer_support"
            ... )
            >>> 
            >>> if result.is_successful():
            ...     print(f"Training completed: {result.model_artifact_s3_uri}")
            ... else:
            ...     print(f"Training failed: {result.error_message}")
        """
        # Validate training data path
        training_data_file = Path(training_data_path)
        if not training_data_file.exists():
            logger.error(
                f"Training data file not found: {training_data_path}",
                extra={"context": {"training_data_path": training_data_path}}
            )
            raise FileNotFoundError(f"Training data file not found: {training_data_path}")
        
        if training_data_file.stat().st_size == 0:
            logger.error(
                f"Training data file is empty: {training_data_path}",
                extra={"context": {"training_data_path": training_data_path}}
            )
            raise ValueError(f"Training data file is empty: {training_data_path}")
        
        logger.info(
            "Starting model training",
            extra={
                "context": {
                    "use_case_name": use_case_name,
                    "training_data_path": training_data_path,
                    "has_custom_hyperparameters": hyperparameters is not None,
                }
            }
        )
        
        # Step 1: Upload training data to S3
        logger.info("Uploading training data to S3")
        s3_data_uri = self._upload_training_data_to_s3(
            training_data_path,
            use_case_name
        )
        logger.info(
            "Training data uploaded to S3",
            extra={"context": {"s3_uri": s3_data_uri}}
        )
        
        # Step 2: Determine hyperparameters if not provided
        if hyperparameters is None:
            logger.info("Determining optimal hyperparameters from dataset")
            
            # Analyze dataset to get recommendations
            try:
                # Analyze the dataset directly
                dataset_analysis = self._analyze_training_dataset(training_data_path)
                
                # Determine hyperparameters based on analysis
                hyperparameters = self._determine_hyperparameters(dataset_analysis)
                
                logger.info(
                    "Hyperparameters determined from dataset analysis",
                    extra={
                        "context": {
                            "hyperparameters": hyperparameters,
                            "dataset_size": dataset_analysis.num_examples,
                        }
                    }
                )
            except Exception as e:
                # If analysis fails, fall back to default hyperparameters
                logger.warning(
                    f"Failed to analyze dataset, using default hyperparameters: {e}",
                    extra={"context": {"error": str(e)}}
                )
                hyperparameters = self._get_default_hyperparameters()
                logger.info(
                    "Using default hyperparameters",
                    extra={"context": {"hyperparameters": hyperparameters}}
                )
        else:
            logger.info(
                "Using provided hyperparameters",
                extra={"context": {"hyperparameters": hyperparameters}}
            )
        
        # Step 3: Create and start SageMaker training job
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        job_name = f"{use_case_name}-training-{timestamp}"
        
        logger.info(
            "Creating SageMaker training job",
            extra={
                "context": {
                    "job_name": job_name,
                    "base_model": self.config.base_model,
                    "instance_type": self.config.training_instance_type,
                }
            }
        )
        
        try:
            # Create training job using JumpStartEstimator
            training_job_response = self._create_training_job(
                job_name=job_name,
                s3_data_uri=s3_data_uri,
                hyperparameters=hyperparameters
            )
            
            # Get the actual job name (JumpStart may modify it)
            actual_job_name = training_job_response.get('TrainingJobName', job_name)
            
            logger.info(
                "Training job created successfully",
                extra={
                    "context": {
                        "requested_job_name": job_name,
                        "actual_job_name": actual_job_name,
                        "training_job_arn": training_job_response.get('TrainingJobArn', 'N/A'),
                    }
                }
            )
            
        except Exception as e:
            logger.error(
                f"Failed to create training job: {e}",
                extra={
                    "context": {
                        "job_name": job_name,
                        "error": str(e),
                    }
                }
            )
            raise RuntimeError(f"Failed to create training job: {e}")
        
        # Step 4: Wait for training completion
        logger.info(
            "Waiting for training job to complete",
            extra={"context": {"job_name": actual_job_name}}
        )
        
        result = self._wait_for_training(actual_job_name)
        
        if result.is_successful():
            logger.info(
                "Training completed successfully",
                extra={
                    "context": {
                        "job_name": result.job_name,
                        "model_artifact_uri": result.model_artifact_s3_uri,
                        "training_time_seconds": result.training_time_seconds,
                        "final_loss": result.final_loss,
                    }
                }
            )
        else:
            logger.error(
                "Training failed",
                extra={
                    "context": {
                        "job_name": result.job_name,
                        "status": result.status,
                        "error_message": result.error_message,
                    }
                }
            )
        
        return result
    
    def _upload_training_data_to_s3(
        self,
        training_data_path: str,
        use_case_name: str
    ) -> str:
        """
        Upload training data file to S3.
        
        Uploads the JSONL training data file to the configured S3 bucket
        in a structured path for organization.
        
        Args:
            training_data_path: Local path to the training data file
            use_case_name: Name of the use case for organizing S3 paths
        
        Returns:
            str: S3 URI of the uploaded training data (s3://bucket/path/file.jsonl)
        
        Raises:
            IOError: If upload fails
        """
        import boto3
        
        # Create S3 client
        s3_client = boto3.client('s3', region_name=self.config.aws_region)
        
        # Generate S3 key
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        filename = Path(training_data_path).name
        s3_key = f"training-data/{use_case_name}/{timestamp}/{filename}"
        
        logger.debug(
            "Uploading file to S3",
            extra={
                "context": {
                    "local_path": training_data_path,
                    "s3_bucket": self.config.s3_bucket,
                    "s3_key": s3_key,
                }
            }
        )
        
        try:
            # Upload file
            s3_client.upload_file(
                Filename=training_data_path,
                Bucket=self.config.s3_bucket,
                Key=s3_key
            )
            
            # Construct S3 URI
            s3_uri = f"s3://{self.config.s3_bucket}/{s3_key}"
            
            logger.debug(
                "File uploaded successfully",
                extra={"context": {"s3_uri": s3_uri}}
            )
            
            return s3_uri
            
        except Exception as e:
            logger.error(
                f"Failed to upload training data to S3: {e}",
                extra={
                    "context": {
                        "training_data_path": training_data_path,
                        "s3_bucket": self.config.s3_bucket,
                        "s3_key": s3_key,
                        "error": str(e),
                    }
                }
            )
            raise IOError(f"Failed to upload training data to S3: {e}")
    
    def _analyze_training_dataset(self, dataset_path: str) -> DatasetAnalysis:
        """
        Analyze training dataset to extract statistics.
        
        Reads a JSONL training dataset file and computes statistics including
        the number of examples, average instruction length, and average response
        length. Based on the dataset size, recommends optimal training parameters.
        
        Args:
            dataset_path: Path to the JSONL file containing training examples
        
        Returns:
            DatasetAnalysis: Analysis results with statistics and recommendations
        
        Raises:
            FileNotFoundError: If dataset_path does not exist
            ValueError: If dataset file is empty or contains invalid JSON
        """
        # Validate dataset path exists
        dataset_file = Path(dataset_path)
        if not dataset_file.exists():
            raise FileNotFoundError(f"Dataset file not found: {dataset_path}")
        
        logger.info(
            "Analyzing training dataset",
            extra={"context": {"dataset_path": dataset_path}}
        )
        
        # Initialize counters
        num_examples = 0
        total_instruction_length = 0
        total_response_length = 0
        
        # Read and analyze JSONL file
        with open(dataset_path, 'r', encoding='utf-8') as f:
            for line_num, line in enumerate(f, start=1):
                line = line.strip()
                
                # Skip empty lines
                if not line:
                    continue
                
                try:
                    # Parse JSON
                    example = json.loads(line)
                    
                    # Validate required fields
                    if 'instruction' not in example or 'response' not in example:
                        logger.warning(
                            f"Skipping line {line_num}: missing required fields",
                            extra={
                                "context": {
                                    "line_num": line_num,
                                    "has_instruction": 'instruction' in example,
                                    "has_response": 'response' in example,
                                }
                            }
                        )
                        continue
                    
                    # Count example
                    num_examples += 1
                    
                    # Accumulate lengths
                    instruction = example.get('instruction', '')
                    response = example.get('response', '')
                    
                    total_instruction_length += len(instruction)
                    total_response_length += len(response)
                    
                except json.JSONDecodeError as e:
                    logger.warning(
                        f"Skipping line {line_num}: invalid JSON",
                        extra={
                            "context": {
                                "line_num": line_num,
                                "error": str(e),
                            }
                        }
                    )
                    continue
        
        # Validate we found at least one example
        if num_examples == 0:
            raise ValueError(
                f"Dataset file is empty or contains no valid examples: {dataset_path}"
            )
        
        # Calculate averages
        avg_instruction_length = total_instruction_length // num_examples
        avg_response_length = total_response_length // num_examples
        
        # Recommend training parameters based on dataset size
        if num_examples >= 1000:
            # Large dataset: fewer epochs, larger batch size
            recommended_epochs = 3
            recommended_batch_size = 32
        elif num_examples >= 500:
            # Medium dataset: medium epochs, medium batch size
            recommended_epochs = 5
            recommended_batch_size = 16
        elif num_examples >= 200:
            # Small-medium dataset: more epochs, smaller batch size
            recommended_epochs = 7
            recommended_batch_size = 8
        else:
            # Small dataset: most epochs, smallest batch size
            recommended_epochs = 10
            recommended_batch_size = 4
        
        # Create analysis result
        analysis = DatasetAnalysis(
            num_examples=num_examples,
            avg_instruction_length=avg_instruction_length,
            avg_response_length=avg_response_length,
            recommended_epochs=recommended_epochs,
            recommended_batch_size=recommended_batch_size
        )
        
        logger.info(
            "Dataset analysis completed",
            extra={
                "context": {
                    "num_examples": num_examples,
                    "avg_instruction_length": avg_instruction_length,
                    "avg_response_length": avg_response_length,
                    "recommended_epochs": recommended_epochs,
                    "recommended_batch_size": recommended_batch_size,
                }
            }
        )
        
        return analysis
    
    def _determine_hyperparameters(self, dataset_analysis: DatasetAnalysis) -> Dict[str, Any]:
        """
        Calculate optimal hyperparameters based on dataset analysis.
        
        Determines training hyperparameters optimized for the specific dataset
        characteristics. The method follows these principles:
        - Larger datasets → fewer epochs, smaller learning rate
        - Smaller datasets → more epochs, larger learning rate
        - Batch size is always a power of 2 for optimal GPU utilization
        - LoRA parameters are adjusted based on dataset complexity
        
        The learning rate is inversely related to dataset size to prevent
        overfitting on large datasets and ensure sufficient learning on small datasets.
        
        Args:
            dataset_analysis: DatasetAnalysis object containing dataset statistics
                            including num_examples, avg_instruction_length,
                            avg_response_length, recommended_epochs, and
                            recommended_batch_size.
        
        Returns:
            Dict[str, Any]: Dictionary of hyperparameter names and values:
                - epochs: Number of training epochs (from dataset_analysis)
                - learning_rate: Learning rate inversely scaled with dataset size
                - per_device_train_batch_size: Batch size (power of 2, from dataset_analysis)
                - lora_r: LoRA rank parameter (8-16 based on dataset size)
                - lora_alpha: LoRA alpha parameter (2x lora_r)
                - lora_dropout: LoRA dropout rate (0.1)
        
        Example:
            >>> from src.config_models import DatasetAnalysis
            >>> analysis = DatasetAnalysis(
            ...     num_examples=1000,
            ...     avg_instruction_length=100,
            ...     avg_response_length=200,
            ...     recommended_epochs=3,
            ...     recommended_batch_size=32
            ... )
            >>> trainer = ModelTrainer(sagemaker_client, config)
            >>> hyperparams = trainer._determine_hyperparameters(analysis)
            >>> print(hyperparams['epochs'])  # 3
            >>> print(hyperparams['learning_rate'])  # 0.0001 (smaller for large dataset)
        """
        logger.info(
            "Determining hyperparameters from dataset analysis",
            extra={
                "context": {
                    "num_examples": dataset_analysis.num_examples,
                    "recommended_epochs": dataset_analysis.recommended_epochs,
                    "recommended_batch_size": dataset_analysis.recommended_batch_size,
                }
            }
        )
        
        # Use recommended epochs from dataset analysis
        epochs = dataset_analysis.recommended_epochs
        
        # Use recommended batch size from dataset analysis (already power of 2)
        batch_size = dataset_analysis.recommended_batch_size
        
        # Calculate learning rate inversely proportional to dataset size
        # Base learning rate: 0.0002 for small datasets
        # Scale down for larger datasets to prevent overfitting
        if dataset_analysis.num_examples >= 1000:
            # Large dataset: smaller learning rate
            learning_rate = 0.0001
        elif dataset_analysis.num_examples >= 500:
            # Medium dataset: medium learning rate
            learning_rate = 0.00015
        elif dataset_analysis.num_examples >= 200:
            # Small-medium dataset: larger learning rate
            learning_rate = 0.0002
        else:
            # Small dataset: largest learning rate
            learning_rate = 0.0003
        
        # Adjust LoRA rank based on dataset size
        # Larger datasets benefit from higher rank (more parameters)
        if dataset_analysis.num_examples >= 1000:
            lora_r = 16
        elif dataset_analysis.num_examples >= 500:
            lora_r = 12
        else:
            lora_r = 8
        
        # LoRA alpha is typically 2x the rank
        lora_alpha = lora_r * 2
        
        # LoRA dropout is fixed at 0.1 (standard value)
        lora_dropout = 0.1
        
        # Construct hyperparameters dictionary
        hyperparameters = {
            "epochs": str(epochs),
            "learning_rate": str(learning_rate),
            "per_device_train_batch_size": str(batch_size),
            "lora_r": str(lora_r),
            "lora_alpha": str(lora_alpha),
            "lora_dropout": str(lora_dropout),
        }
        
        logger.info(
            "Hyperparameters determined",
            extra={
                "context": {
                    "hyperparameters": hyperparameters,
                    "dataset_size": dataset_analysis.num_examples,
                }
            }
        )
        
        return hyperparameters
    
    def _get_default_hyperparameters(self) -> Dict[str, Any]:
        """
        Get default training hyperparameters.
        
        Returns a set of default hyperparameters suitable for most use cases.
        This is used as a fallback when dataset analysis is not available.
        
        Returns:
            Dict[str, Any]: Dictionary of hyperparameter names and values
        """
        return {
            "epochs": "3",
            "learning_rate": "0.0001",
            "per_device_train_batch_size": "8",
            "lora_r": "8",
            "lora_alpha": "16",
            "lora_dropout": "0.1",
        }
    
    def _create_training_job(
        self,
        job_name: str,
        s3_data_uri: str,
        hyperparameters: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Create a SageMaker training job using JumpStartEstimator.
        
        Creates a training job using the SageMaker JumpStart SDK with the specified
        configuration, hyperparameters, and training data. This method uses the
        high-level JumpStartEstimator API which automatically handles:
        - Training image resolution for the model
        - EULA acceptance for Llama models
        - Proper hyperparameter formatting
        - Training job creation and monitoring
        
        Args:
            job_name: Unique name for the training job
            s3_data_uri: S3 URI of the training data
            hyperparameters: Dictionary of training hyperparameters
        
        Returns:
            Dict[str, Any]: Response containing training job details
        
        Raises:
            Exception: If training job creation fails
        """
        logger.info(
            "Creating training job with JumpStartEstimator",
            extra={
                "context": {
                    "job_name": job_name,
                    "s3_data_uri": s3_data_uri,
                    "model_id": "meta-textgeneration-llama-3-2-3b-instruct",
                }
            }
        )
        
        # Convert hyperparameters to JumpStart format
        jumpstart_hyperparameters = {
            "chat_dataset": "False",
            "instruction_tuned": "True",
            "use_default_template": "True",
            "disable_output_compression": "False",
            "epoch": str(hyperparameters.get("epochs", 1)),
            "max_steps": str(hyperparameters.get("max_steps", 100)),
            "learning_rate": str(hyperparameters.get("learning_rate", 1e-4)),
            "per_device_train_batch_size": str(hyperparameters.get("per_device_train_batch_size", 1)),
            "per_device_eval_batch_size": str(hyperparameters.get("per_device_train_batch_size", 1)),
            "validation_split_ratio": str(hyperparameters.get("validation_split", 0.05)),
            "preprocessing_num_workers": "0",
            "num_workers_dataloader": "0",
            "max_input_length": "2048",
            "gradient_accumulation_steps": "4",
            "lora_r": str(hyperparameters.get("lora_r", 16)),
            "lora_alpha": str(hyperparameters.get("lora_alpha", 64)),
            "lora_dropout": str(hyperparameters.get("lora_dropout", 0.05)),
            "target_modules": "q_proj,k_proj,v_proj,o_proj"
        }
        
        logger.debug(
            "JumpStart hyperparameters configured",
            extra={
                "context": {
                    "hyperparameters": jumpstart_hyperparameters,
                }
            }
        )
        
        try:
            # Create JumpStartEstimator
            estimator = JumpStartEstimator(
                model_id="meta-textgeneration-llama-3-2-3b-instruct",
                role=self.config.sagemaker_role_arn,
                instance_count=1,
                instance_type=self.config.training_instance_type,
                sagemaker_session=self.sagemaker_session,
                environment={
                    "accept_eula": "true"  # Required for Llama models
                },
                hyperparameters=jumpstart_hyperparameters,
                output_path=f"s3://{self.config.s3_bucket}/model-artifacts/",
                base_job_name=job_name
            )
            
            logger.info(
                "JumpStartEstimator created successfully",
                extra={
                    "context": {
                        "job_name": job_name,
                        "instance_type": self.config.training_instance_type,
                    }
                }
            )
            
            # Prepare training input
            training_input = TrainingInput(
                s3_data=s3_data_uri,
                content_type="application/jsonlines"
            )
            
            logger.info(
                "Starting training job with JumpStart",
                extra={
                    "context": {
                        "job_name": job_name,
                        "s3_data_uri": s3_data_uri,
                    }
                }
            )
            
            # Start training (non-blocking)
            estimator.fit({"training": training_input}, wait=False)
            
            # Store estimator for potential later use (e.g., deployment)
            self._current_estimator = estimator
            
            # Get the actual training job name (JumpStart may modify it)
            actual_job_name = estimator.latest_training_job.name
            
            logger.info(
                "Training job started successfully",
                extra={
                    "context": {
                        "requested_job_name": job_name,
                        "actual_job_name": actual_job_name,
                    }
                }
            )
            
            # Return response in format expected by caller
            return {
                "TrainingJobArn": f"arn:aws:sagemaker:{self.config.aws_region}:*:training-job/{actual_job_name}",
                "TrainingJobName": actual_job_name,
                "Estimator": estimator
            }
            
        except Exception as e:
            logger.error(
                f"Failed to create training job with JumpStart: {e}",
                extra={
                    "context": {
                        "job_name": job_name,
                        "error": str(e),
                        "error_type": type(e).__name__,
                    }
                },
                exc_info=True
            )
            raise RuntimeError(f"Failed to create training job: {e}") from e
    
    def _wait_for_training(
        self,
        job_name: str,
        poll_interval: int = 60
    ) -> TrainingResult:
        """
        Wait for training job to complete with polling.
        
        Polls the SageMaker training job status at regular intervals until
        the job completes (successfully or with failure) or times out.
        
        Args:
            job_name: Name of the training job to monitor
            poll_interval: Seconds to wait between status checks (default: 60)
        
        Returns:
            TrainingResult: Training result with job details and status
        
        Raises:
            RuntimeError: If unable to get job status
        """
        logger.info(
            "Starting training job monitoring",
            extra={
                "context": {
                    "job_name": job_name,
                    "poll_interval": poll_interval,
                }
            }
        )
        
        start_time = time.time()
        last_status = None
        
        while True:
            try:
                # Get training job status
                response = self.sagemaker_client.describe_training_job(
                    TrainingJobName=job_name
                )
                
                status = response['TrainingJobStatus']
                
                # Log status changes
                if status != last_status:
                    logger.info(
                        f"Training job status: {status}",
                        extra={
                            "context": {
                                "job_name": job_name,
                                "status": status,
                                "elapsed_seconds": int(time.time() - start_time),
                            }
                        }
                    )
                    last_status = status
                
                # Check if training is complete
                if status in ['Completed', 'Failed', 'Stopped']:
                    # Calculate training time
                    training_start = response.get('TrainingStartTime')
                    training_end = response.get('TrainingEndTime')
                    
                    if training_start and training_end:
                        training_time_seconds = int(
                            (training_end - training_start).total_seconds()
                        )
                    else:
                        training_time_seconds = int(time.time() - start_time)
                    
                    # Extract model artifact URI
                    model_artifact_uri = response.get('ModelArtifacts', {}).get(
                        'S3ModelArtifacts', ''
                    )
                    
                    # Extract final loss (if available)
                    final_loss = 0.0
                    final_metrics = response.get('FinalMetricDataList', [])
                    for metric in final_metrics:
                        if metric.get('MetricName') == 'train:loss':
                            final_loss = metric.get('Value', 0.0)
                            break
                    
                    # Extract error message if failed
                    error_message = None
                    if status in ['Failed', 'Stopped']:
                        error_message = response.get('FailureReason', 'Unknown error')
                    
                    # Create result
                    result = TrainingResult(
                        job_name=job_name,
                        model_artifact_s3_uri=model_artifact_uri,
                        training_time_seconds=training_time_seconds,
                        final_loss=final_loss,
                        status=status,
                        error_message=error_message
                    )
                    
                    logger.info(
                        f"Training job finished with status: {status}",
                        extra={
                            "context": {
                                "job_name": job_name,
                                "status": status,
                                "training_time_seconds": training_time_seconds,
                                "model_artifact_uri": model_artifact_uri,
                            }
                        }
                    )
                    
                    return result
                
                # Wait before next poll
                logger.debug(
                    f"Training in progress, waiting {poll_interval} seconds...",
                    extra={
                        "context": {
                            "job_name": job_name,
                            "status": status,
                        }
                    }
                )
                time.sleep(poll_interval)
                
            except Exception as e:
                logger.error(
                    f"Error checking training job status: {e}",
                    extra={
                        "context": {
                            "job_name": job_name,
                            "error": str(e),
                        }
                    }
                )
                raise RuntimeError(f"Failed to monitor training job: {e}")
    
    def cleanup_training_artifacts(
        self,
        job_name: str,
        retention_days: int = 7
    ) -> None:
        """
        Delete training artifacts after retention period.
        
        Cleans up S3 training artifacts (training data, model artifacts) associated
        with a training job after the specified retention period. This method is
        idempotent and safe to call multiple times - it will not fail if artifacts
        have already been deleted.
        
        The method:
        1. Checks if artifacts are older than the retention period
        2. Deletes S3 training data used for the job
        3. Deletes S3 model artifacts produced by the job
        4. Logs all cleanup operations
        5. Handles errors gracefully (doesn't fail if artifacts already deleted)
        
        Args:
            job_name: Name of the training job whose artifacts should be cleaned up.
                     This is the SageMaker training job name returned by train_model().
            retention_days: Number of days to retain artifacts before deletion.
                          Artifacts older than this will be deleted. Default is 7 days.
                          Set to 0 to delete immediately regardless of age.
        
        Raises:
            ValueError: If job_name is None or empty
            ValueError: If retention_days is negative
            RuntimeError: If unable to describe training job or access S3
        
        Example:
            >>> from src.aws_client_manager import AWSClientManager
            >>> from src.configuration_manager import ConfigurationManager
            >>> 
            >>> # Initialize components
            >>> config_manager = ConfigurationManager()
            >>> pipeline_config = config_manager.load_pipeline_config()
            >>> aws_manager = AWSClientManager({'region': pipeline_config.aws_region})
            >>> sagemaker_client = aws_manager.get_sagemaker_client()
            >>> 
            >>> # Create trainer
            >>> trainer = ModelTrainer(sagemaker_client, pipeline_config)
            >>> 
            >>> # Train model
            >>> result = trainer.train_model(
            ...     training_data_path="event_files/training_data/dataset.jsonl",
            ...     use_case_name="customer_support"
            ... )
            >>> 
            >>> # Later, cleanup old artifacts (after 7 days)
            >>> trainer.cleanup_training_artifacts(
            ...     job_name=result.job_name,
            ...     retention_days=7
            ... )
        """
        import boto3
        from datetime import datetime, timedelta
        
        # Validate job_name parameter
        if not job_name:
            raise ValueError("job_name cannot be None or empty")
        
        # Validate retention_days parameter
        if retention_days < 0:
            raise ValueError(f"retention_days must be non-negative, got {retention_days}")
        
        logger.info(
            "Starting cleanup of training artifacts",
            extra={
                "context": {
                    "job_name": job_name,
                    "retention_days": retention_days,
                }
            }
        )
        
        try:
            # Get training job details to find artifact locations
            response = self.sagemaker_client.describe_training_job(
                TrainingJobName=job_name
            )
            
            # Extract training job creation time
            creation_time = response.get('CreationTime')
            if not creation_time:
                logger.warning(
                    f"Could not determine creation time for job {job_name}, skipping age check",
                    extra={"context": {"job_name": job_name}}
                )
                # If we can't determine age, assume it's old enough to clean
                creation_time = datetime.now() - timedelta(days=retention_days + 1)
            
            # Check if artifacts are older than retention period
            age_days = (datetime.now(creation_time.tzinfo) - creation_time).days
            
            if age_days < retention_days:
                logger.info(
                    f"Training artifacts are only {age_days} days old, retention period is {retention_days} days. Skipping cleanup.",
                    extra={
                        "context": {
                            "job_name": job_name,
                            "age_days": age_days,
                            "retention_days": retention_days,
                        }
                    }
                )
                return
            
            logger.info(
                f"Training artifacts are {age_days} days old, exceeding retention period of {retention_days} days. Proceeding with cleanup.",
                extra={
                    "context": {
                        "job_name": job_name,
                        "age_days": age_days,
                        "retention_days": retention_days,
                    }
                }
            )
            
            # Create S3 client
            s3_client = boto3.client('s3', region_name=self.config.aws_region)
            
            # Track cleanup statistics
            deleted_objects = []
            
            # Step 1: Delete training data from S3
            # Training data is stored in InputDataConfig
            input_data_config = response.get('InputDataConfig', [])
            for input_channel in input_data_config:
                s3_data_source = input_channel.get('DataSource', {}).get('S3DataSource', {})
                s3_uri = s3_data_source.get('S3Uri', '')
                
                if s3_uri:
                    logger.info(
                        f"Deleting training data from {s3_uri}",
                        extra={"context": {"s3_uri": s3_uri}}
                    )
                    
                    try:
                        deleted_count = self._delete_s3_objects(s3_client, s3_uri)
                        deleted_objects.append({
                            'type': 'training_data',
                            'uri': s3_uri,
                            'count': deleted_count
                        })
                        
                        logger.info(
                            f"Deleted {deleted_count} training data objects from {s3_uri}",
                            extra={
                                "context": {
                                    "s3_uri": s3_uri,
                                    "deleted_count": deleted_count,
                                }
                            }
                        )
                    except Exception as e:
                        # Log error but continue with other artifacts
                        logger.warning(
                            f"Failed to delete training data from {s3_uri}: {e}",
                            extra={
                                "context": {
                                    "s3_uri": s3_uri,
                                    "error": str(e),
                                }
                            }
                        )
            
            # Step 2: Delete model artifacts from S3
            model_artifacts = response.get('ModelArtifacts', {})
            model_artifact_uri = model_artifacts.get('S3ModelArtifacts', '')
            
            if model_artifact_uri:
                logger.info(
                    f"Deleting model artifacts from {model_artifact_uri}",
                    extra={"context": {"s3_uri": model_artifact_uri}}
                )
                
                try:
                    deleted_count = self._delete_s3_objects(s3_client, model_artifact_uri)
                    deleted_objects.append({
                        'type': 'model_artifacts',
                        'uri': model_artifact_uri,
                        'count': deleted_count
                    })
                    
                    logger.info(
                        f"Deleted {deleted_count} model artifact objects from {model_artifact_uri}",
                        extra={
                            "context": {
                                "s3_uri": model_artifact_uri,
                                "deleted_count": deleted_count,
                            }
                        }
                    )
                except Exception as e:
                    # Log error but continue
                    logger.warning(
                        f"Failed to delete model artifacts from {model_artifact_uri}: {e}",
                        extra={
                            "context": {
                                "s3_uri": model_artifact_uri,
                                "error": str(e),
                            }
                        }
                    )
            
            # Log summary of cleanup
            total_deleted = sum(obj['count'] for obj in deleted_objects)
            logger.info(
                f"Cleanup completed for training job {job_name}",
                extra={
                    "context": {
                        "job_name": job_name,
                        "total_objects_deleted": total_deleted,
                        "deleted_objects": deleted_objects,
                    }
                }
            )
            
        except self.sagemaker_client.exceptions.ResourceNotFound:
            # Training job doesn't exist - artifacts may have already been cleaned
            logger.info(
                f"Training job {job_name} not found. Artifacts may have already been cleaned up.",
                extra={"context": {"job_name": job_name}}
            )
        except Exception as e:
            # Log error but don't raise - cleanup should be best-effort
            logger.error(
                f"Error during cleanup of training artifacts for job {job_name}: {e}",
                extra={
                    "context": {
                        "job_name": job_name,
                        "error": str(e),
                    }
                }
            )
            # Re-raise as RuntimeError for critical failures
            if "AccessDenied" in str(e) or "InvalidAccessKeyId" in str(e):
                raise RuntimeError(f"Failed to cleanup training artifacts due to access error: {e}")
    
    def _delete_s3_objects(self, s3_client, s3_uri: str) -> int:
        """
        Delete objects from S3 given an S3 URI.
        
        Handles both single objects and prefixes (directories). For prefixes,
        deletes all objects under that prefix.
        
        Args:
            s3_client: Boto3 S3 client
            s3_uri: S3 URI (s3://bucket/key or s3://bucket/prefix/)
        
        Returns:
            int: Number of objects deleted
        
        Raises:
            ValueError: If s3_uri is not a valid S3 URI
            Exception: If S3 operations fail
        """
        # Parse S3 URI
        if not s3_uri.startswith('s3://'):
            raise ValueError(f"Invalid S3 URI: {s3_uri}")
        
        # Remove s3:// prefix and split bucket and key
        uri_parts = s3_uri[5:].split('/', 1)
        bucket = uri_parts[0]
        key = uri_parts[1] if len(uri_parts) > 1 else ''
        
        logger.debug(
            f"Deleting S3 objects",
            extra={
                "context": {
                    "bucket": bucket,
                    "key": key,
                }
            }
        )
        
        deleted_count = 0
        
        try:
            # Check if this is a single object or a prefix
            # Try to list objects with this prefix
            paginator = s3_client.get_paginator('list_objects_v2')
            pages = paginator.paginate(Bucket=bucket, Prefix=key)
            
            # Collect all objects to delete
            objects_to_delete = []
            for page in pages:
                if 'Contents' in page:
                    for obj in page['Contents']:
                        objects_to_delete.append({'Key': obj['Key']})
            
            # Delete objects in batches (S3 allows up to 1000 per request)
            if objects_to_delete:
                # Delete in batches of 1000
                batch_size = 1000
                for i in range(0, len(objects_to_delete), batch_size):
                    batch = objects_to_delete[i:i + batch_size]
                    
                    response = s3_client.delete_objects(
                        Bucket=bucket,
                        Delete={'Objects': batch}
                    )
                    
                    # Count successfully deleted objects
                    deleted = response.get('Deleted', [])
                    deleted_count += len(deleted)
                    
                    # Log any errors
                    errors = response.get('Errors', [])
                    for error in errors:
                        logger.warning(
                            f"Failed to delete S3 object: {error.get('Key')}",
                            extra={
                                "context": {
                                    "key": error.get('Key'),
                                    "code": error.get('Code'),
                                    "message": error.get('Message'),
                                }
                            }
                        )
                
                logger.debug(
                    f"Deleted {deleted_count} objects from s3://{bucket}/{key}",
                    extra={
                        "context": {
                            "bucket": bucket,
                            "key": key,
                            "deleted_count": deleted_count,
                        }
                    }
                )
            else:
                logger.debug(
                    f"No objects found at s3://{bucket}/{key}",
                    extra={
                        "context": {
                            "bucket": bucket,
                            "key": key,
                        }
                    }
                )
        
        except s3_client.exceptions.NoSuchBucket:
            logger.warning(
                f"S3 bucket does not exist: {bucket}",
                extra={"context": {"bucket": bucket}}
            )
        except s3_client.exceptions.NoSuchKey:
            logger.debug(
                f"S3 object does not exist: s3://{bucket}/{key}",
                extra={
                    "context": {
                        "bucket": bucket,
                        "key": key,
                    }
                }
            )
        
        return deleted_count
